version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-docker-devops"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sxb9gpgsg5pf"
s3_prefix = "my-docker-devops"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"